# Hadolint configuration file

# Configure ignore rules
# https://github.com/hadolint/hadolint#rules for a list of available rules.
# Online Linter
# https://hadolint.github.io/hadolint/
ignored:
  - DL3008
  - DL3009
  - DL3013
  - DL3015
  - DL3042
trustedRegistries:
  - docker.io
  - ghcr.io
