# Online Linter: https://hadolint.github.io/hadolint/
# Rules:         https://github.com/hadolint/hadolint?tab=readme-ov-file#rules
ignored:
  - DL3008
  - DL3009
  - DL3013
  - DL3015
  - DL3042
trustedRegistries:
  - docker.io
  - ghcr.io
